# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
cache: pip
python:
  - 3.4.5
before_install:
  - npm install -g bower
install:
  - pushd app
  - pip install -r requirements/dev.txt
  - bower install --force
  - popd
script:
  - pushd app
  - flask lint
  - flask assets build
  - flask test
  - popd
