# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
cache: pip
python:
  - 3.4.5
env:
  - FLASK_APP=app/autoapp.py
before_install:
  - npm install bower
install:
  - pushd app
  - pip install -r requirements/dev.txt
  - bower install --force
  - popd
before_script: flask lint
script: flask test
