# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
cache: pip
python:
  - 3.4.5
before_install:
  - npm install -g bower
install:
  - ./travis-scripts/install.sh
script:
  - ./travis-scripts/build.sh
  - ./travis-scripts/test.sh
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && if [ -z "$TRAVIS_TAG" ]; then
      ./deploy.sh
    fi
deploy:
  provider: releases
  on:
    tags: true
