# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.4
env:
  - FLASK_APP=autoapp.py
install: pip install -r requirements/dev.txt
before_script: flask lint
script: flask test
