# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
cache: pip
python:
  - 3.4.5
services:
  - docker
install:
  - ./travis-scripts/install.sh
script:
  - ./travis-scripts/build_assets.sh \
    AWS_ACCESS_KEY=$AWS_ACCESS_KEY \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
  - ./travis-scripts/test.sh
  - ./travis-scripts/build_images.sh
after_success:
  - ./travis-scripts/deploy.sh
provider: releases
on:
  tags: true
